/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelBP;


import Option.SiNoDialog;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import licoreriawilma.Producto;
import licoreriawilma.TipoProducto;

/**
 *
 * @author henrryagc
 */
public class PanelBP extends javax.swing.JPanel {

    /**
     * Creates new form PanelBP
     */
    private Object[][] obj;
    private int fila;
    //int numero ;
    //String nomSearch;
    
    public PanelBP() {
        initComponents();
        

       //numero = 0;
        Limpiar();//Metodo para limpiar campos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(212, 66, 0));
        setMaximumSize(new java.awt.Dimension(920, 560));
        setPreferredSize(new java.awt.Dimension(920, 560));

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel1.setText("BUSCAR PRODUCTOS PARA HACER ALGUNOS AJUSTES");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPO DE PRODUCTO");

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE DEL PRODUCTO");

        jButton1.setBackground(new java.awt.Color(215, 215, 13));
        jButton1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchB-25.png"))); // NOI18N
        jButton1.setText("BUSCAR PRODUCTO");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jTextField1.setText("jTextField1");

        jTable1.setBackground(new java.awt.Color(0, 102, 204));
        jTable1.setFont(new java.awt.Font("Fira Code Medium", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "PRODUCTO", "TIPO PRODUCTO", "STOCK", "PRECIO"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(212, 114, 57));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel4.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATOS OBTENIDOS");

        jLabel5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Producto:");

        jTextField3.setFont(new java.awt.Font("Courier 10 Pitch", 0, 17)); // NOI18N
        jTextField3.setText("jTextField3");
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jTextField3.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre del Producto:");

        jTextField4.setFont(new java.awt.Font("Courier 10 Pitch", 0, 17)); // NOI18N
        jTextField4.setText("jTextField4");
        jTextField4.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jTextField4.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio del Producto:");

        jTextField5.setFont(new java.awt.Font("Courier 10 Pitch", 0, 17)); // NOI18N
        jTextField5.setText("jTextField5");
        jTextField5.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jTextField5.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("S/.");

        jLabel8.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad del Producto:");

        jTextField6.setFont(new java.awt.Font("Courier 10 Pitch", 0, 17)); // NOI18N
        jTextField6.setText("jTextField6");
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jTextField6.setEnabled(false);

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 22)); // NOI18N
        jButton2.setText("ACTUALIZAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 22)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 51));
        jCheckBox1.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jCheckBox1.setText("¿Editar?");
        jCheckBox1.setToolTipText("Marcar");
        jCheckBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setOpaque(true);
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 51));
        jCheckBox2.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jCheckBox2.setText("¿Editar?");
        jCheckBox2.setToolTipText("Marcar");
        jCheckBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jCheckBox2.setBorderPainted(true);
        jCheckBox2.setOpaque(true);
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 51));
        jCheckBox3.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jCheckBox3.setText("¿Editar?");
        jCheckBox3.setToolTipText("Marcar");
        jCheckBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jCheckBox3.setBorderPainted(true);
        jCheckBox3.setOpaque(true);
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 51));
        jCheckBox4.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jCheckBox4.setText("¿Editar?");
        jCheckBox4.setToolTipText("Marcar");
        jCheckBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jCheckBox4.setBorderPainted(true);
        jCheckBox4.setOpaque(true);
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton3)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3))
        );

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 2, true));
        jRadioButton1.setBorderPainted(true);
        jRadioButton1.setOpaque(true);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true));
        jRadioButton2.setBorderPainted(true);
        jRadioButton2.setOpaque(true);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 2, true));
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Courier 10 Pitch", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TODO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jRadioButton1))
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jRadioButton3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //Button para buscar
        //var selected = jCheckBox1.isSelected();
        cargarListaSearch();//Cargar lista del registro buscado
        Limpiar(); // Dejamos limpias  las cajas de texto
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        
        if (jCheckBox1.isSelected()) {
            jTextField3.setEnabled(true);
        }else{
            jTextField3.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jTextField4.setEnabled(true);
        }else{
            jTextField4.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
        if (jCheckBox3.isSelected()) {
            jTextField5.setEnabled(true);
        }else{
            jTextField5.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()) {
            jTextField6.setEnabled(true);
        }else{
            jTextField6.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        // Se actualizaran todos lo datos seleccionados del producto
        int Message = Message("¿Desea actualizar los datos del producto?");
        switch (Message) {
            case 1:
                System.out.println("Se eligio la opcion SI");
                //Funcion para eliminar el registro
                ActualizarDatos(); // Actualizar registro
                break;
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        //Se eliminara el registro seleccionado si y sólo si se desea eliminar el registro
        int Message = Message("¿Desea eliminar el producto?");
        switch (Message) {
            case 1:
                System.out.println("Se eligio la opcion SI");
                //Funcion para eliminar el registro
                DeleteRegistry(); // Eliminar registro
                break;
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         fila = jTable1.getSelectedRow();
                int columna = jTable1.getSelectedColumn();
                System.out.println("Tabla NP-> fila: "+fila +" columna: "+columna);
                jTextField3.setText(String.valueOf(obj[fila][2]));
                jTextField4.setText(String.valueOf(obj[fila][1]));
                jTextField5.setText(String.valueOf(obj[fila][4]));
                jTextField6.setText(String.valueOf(obj[fila][3]));   
    }//GEN-LAST:event_jTable1MouseClicked

    
    private void cargarListaSearch(){
        
        String nomSearch = jTextField1.getText();
        //String nomTP = jTextField2.getText();
        
        int numero = 0;
        if (jRadioButton1.isSelected()) {
            numero = 1;
        }
        else if (jRadioButton2.isSelected()) {
            numero = 2;
        }
        else if(jRadioButton3.isSelected()){
            numero = 3;
        }
        
        //FillTable(); //Aqui cargamos la tabla para visualizar los datos
        
        Producto pro = new Producto("",0,0.0,0);
        obj = pro.listaSearch(true, nomSearch, numero);
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Numero", "Producto", "Tipo Producto", "Stock", "Precio"
            }
        ));
        
    }
    
    private void ActualizarDatos(){
        
        String tp;
        String np;
        String pre;
        String cantidad;
        
        Producto pro = new Producto("",0,0.0,0);//Iniciamos el constructo para usar los metodos de la clase
        String nomPro = String.valueOf(obj[fila][1]);
        int idPro = pro.BuscarIdPro(nomPro,false);
        
        if (jCheckBox1.isSelected()) {
            tp = jTextField3.getText(); //Capturar el nombre a actualizar            
            TipoProducto ntp = new TipoProducto(tp);
            String nombre = String.valueOf(obj[fila][2]);   //Recuperar nombre anterior 
            int idTipoPro = ntp.buscarId(nombre,false);
            ntp.UpdateTP(idTipoPro);
            obj[fila][2] = tp; // asignando un nuevo valor
            jTable1.setValueAt(tp, fila, 2);
        }
        //"Numero", "Producto", "Tipo Producto", "Stock", "Precio"
        if(jCheckBox2.isSelected()){
            np = jTextField4.getText();            
            pro.UpdatePro(np, "nombre",idPro);
            obj[fila][1] = np;
            jTable1.setValueAt(np, fila, 1);
        }
        if (jCheckBox3.isSelected()) {
            pre = jTextField5.getText();
            pro.UpdatePro(pre, "precio", idPro);
            obj[fila][4] = pre;
            jTable1.setValueAt(pre, fila, 4);
        }
        if (jCheckBox4.isSelected()) {
            cantidad = jTextField6.getText();
            pro.UpdatePro(cantidad, "cantidad", idPro);
            obj[fila][3] = cantidad;
            jTable1.setValueAt(cantidad, fila, 3);
        }
        //FillTable();
        //jTable1.setValueAt(pre, ERROR, fila);
    }
    
    private void DeleteRegistry(){
        //Recuperamos el nombre producto
        String nomPro = String.valueOf(obj[fila][1]);
        Producto pro = new Producto("",0,0.0,0);
        System.out.println("NomPro: "+nomPro);
        int id = pro.BuscarIdPro(nomPro,false);
        System.out.println("Producto id a eliminar: "+id);
        pro.DeletePro(id,true);
    }
    

    
    private void Limpiar(){
        jTextField1.setText("");
        //jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private int Message(String message) {
         // el modal: true es para que las ventanas ateriores no puedan ejecutarse mientras el mensaje este visible
         SiNoDialog d = new SiNoDialog(null,true);
         d.SetTextOption( message);  
         d.setVisible(true);
         int a = d.getReturnStatus();
         System.out.println("option " + a);
         
         return a;
    }
}
