
package licoreriawilma;

/**
 *
 * @author henrryagc
 */
import Option.SiNoDialog;
import PanelRV.PanelRV;
import PanelNP.PanelNP;
import PanelBP.PanelBP;
import PanelFirst.PanelFirst;
import PanelRV.ProductoVendido;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JScrollPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class jfmrLicoreria extends javax.swing.JFrame {

    protected boolean presionado_1;
    protected boolean presionado_2;
    protected boolean presionado_3;
    protected boolean presionado_4;
    private final PanelRV panelrv = new PanelRV();
    private final PanelNP panelnp = new PanelNP();
    private final PanelBP panelbp = new PanelBP();
    private final PanelFirst panelfirst = new PanelFirst();

    private JFreeChart chart_1;
    private JFreeChart chart_2;
    
    public jfmrLicoreria() {       
        
        initComponents();
         
        jTabbedPane1.setVisible(false);
        // Inicializamos las variables boleanas antes definidas 
        presionado_1 = false;
        presionado_2 = false;
        presionado_3 = false;
        presionado_4 = false;              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LICORERIA APP");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(60, 60));
        setMinimumSize(new java.awt.Dimension(920, 640));
        setPreferredSize(new java.awt.Dimension(920, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 169, 82));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Fira Code", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LICORERIA SEÑORA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrarventa.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoproducto.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarproducto.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Fira Code", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WILMA");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerveza.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("Grafica de ventas");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Grafica de cuadros de venta");
        jPanel1.setAutoscrolls(true);
        jPanel1.setName(""); // NOI18N

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setText("GUARDAR IMAGEN");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(0, 785, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/img/stockproductos.png")), jPanel1, "Stock de Productos"); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 560));

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 51));
        jButton5.setText("GUARDAR IMAGEN");
        jButton5.setToolTipText("");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(0, 785, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/img/ventasproductos.png")), jPanel2, "Historial de ventas de productos"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setForeground(new java.awt.Color(0, 255, 255));
        jPanel4.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(920, 520));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("AQUI NO HAY NADA", null, jPanel4, "hola desde graficos de barra");

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("Graficos de stock");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*Menu panel principal BOTONES EN BARRA DE MENU, cambiar inconos*/
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        //System.out.println("Jbutton1MouseEntered: "+evt.paramString());
        // cargamos la imagen inicio2.png
        imgMenu_2(1);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        // cargamos la imagen inicio.png evaluada si esta precionada o si es elegida
        // sera elegida en el Mouseclicked del buttoon respectivo
        btnExited(1);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        // cargamos la imagen registrarventa2.png
        imgMenu_2(2);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        // cargamos la imagen inicio.png evaluada si esta precionada o si es elegida
        // sera elegida en el Mouseclicked del buttoon respectivo
        btnExited(2);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        // cargamos la imagen nuevoproducto2.png
        imgMenu_2(3);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        // cargamos la imagen inicio.png evaluada si esta precionada o si es elegida
        // sera elegida en el Mouseclicked del buttoon respectivo
        btnExited(3);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        // cargamos la imagen buscarproducto2.png
        imgMenu_2(4);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        // cargamos la imagen inicio.png evaluada si esta precionada o si es elegida
        // sera elegida en el Mouseclicked del buttoon respectivo
        btnExited(4);

    }//GEN-LAST:event_jButton4MouseExited

    /*
    Eventos Principales '--- MouseClicked ---'  de la barra de MENU
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        imgMenuCombinaciones(1);
        PanelContenido(1);//Este metodo nos ayudara a elegir el panel a mostrar
        //panelrv.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        imgMenuCombinaciones(2);
        PanelContenido(2);//Este metodo nos ayudara a elegir el panel a mostrar

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        imgMenuCombinaciones(3);
        PanelContenido(3);//Este metodo nos ayudara a elegir el panel a mostrar
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        imgMenuCombinaciones(4);
        PanelContenido(4);//Este metodo nos ayudara a elegir el panel a mostrar
    }//GEN-LAST:event_jButton4MouseClicked
    /**
     * Evento de inicio de pantalla nos ayudara a controlar el incio de algunos
     * componenetes desde el arranque de la aplicacion
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        getContentPane().add(panelfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 560));
        panelfirst.revalidate();
        panelfirst.repaint();
        panelfirst.setVisible(true);
        contenidoJPanel1();
        ContenidojPanel2();
        CargarPanelContenido();
    }//GEN-LAST:event_formWindowOpened

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:        
        //Con este metodo podremos crear un archivo png del grafico
        
        int message = Message("¿Dese Guardar una Imagen");
        System.out.println("Guardar imagen: "+message);
        switch(message){
            case 1:
                BtnClick();
                break;
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        int message = Message("¿Dese Guardar una Imagen");
        switch(message){
            case 1:
                BtnClick_1();
                break;
        }        
    }//GEN-LAST:event_jButton6MouseClicked

    /*
  Funciones Adicionales  
     */
// Aqui estan las imagenes cargadas para usarlas en cualquier momento en el boton especificado
    private void imgMenu_1(int nBtn) {
        switch (nBtn) {
            case 1:
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png")));
                break;
            case 2:
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrarventa.png")));
                break;
            case 3:
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoproducto.png")));
                break;
            case 4:
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarproducto.png")));
                break;
        }
    }

    private void imgMenu_2(int nBtn) {
        switch (nBtn) {
            case 1:
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio2.png")));
                break;
            case 2:
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrarventa2.png")));
                break;
            case 3:
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoproducto2.png")));
                break;
            case 4:
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarproducto2.png")));
                break;
        }
    }

    // Aqui se evaluara si el boton utiliza el evento de Mouseclicked
    private void btnExited(int nBtn) {
        switch (nBtn) {
            case 1:
                if (presionado_1) {
                    imgMenu_2(1);

                } else {
                    imgMenu_1(1);

                }
                break;
            case 2:
                if (presionado_2) {
                    imgMenu_2(2);

                } else {
                    imgMenu_1(2);
                }
                break;
            case 3:
                if (presionado_3) {
                    imgMenu_2(3);
                } else {
                    imgMenu_1(3);
                }
                break;
            case 4:
                if (presionado_4) {
                    imgMenu_2(4);
                } else {
                    imgMenu_1(4);
                }
                break;
        }
    }

    // En la siguiente funcion se evaluaran las distintas combinaciones
    // que se realizaran cuando determinado button sea utilizado
    // con el evento Mouseclicked
    private void imgMenuCombinaciones(int nBtn) {
        switch (nBtn) {
            case 1:
                imgMenu_2(1);// button 1
                imgMenu_1(2);// button 2
                imgMenu_1(3);// button 3
                imgMenu_1(4);// button 4
                presionado_1 = true;
                presionado_2 = false;
                presionado_3 = false;
                presionado_4 = false;
                panelfirst.setVisible(false);
                break;
            case 2:
                imgMenu_1(1);// button 1
                imgMenu_2(2);// button 2
                imgMenu_1(3);// button 3
                imgMenu_1(4);// button 4
                presionado_1 = false;
                presionado_2 = true;
                presionado_3 = false;
                presionado_4 = false;
                panelfirst.setVisible(false);
                break;
            case 3:
                imgMenu_1(1);// button 1
                imgMenu_1(2);// button 2
                imgMenu_2(3);// button 3
                imgMenu_1(4);// button 4
                presionado_1 = false;
                presionado_2 = false;
                presionado_3 = true;
                presionado_4 = false;
                panelfirst.setVisible(false);
                break;
            case 4:
                imgMenu_1(1);// button 1
                imgMenu_1(2);// button 2
                imgMenu_1(3);// button 3
                imgMenu_2(4);// button 4
                presionado_1 = false;
                presionado_2 = false;
                presionado_3 = false;
                presionado_4 = true;
                panelfirst.setVisible(false);
                break;
        }
    }

    /**
     * Las funciones creadas serviran para instanciar y crear los diferentes
     * paneles para cada caso en los botones
     */
    private void CargarPanelContenido() {
        // 1- Panel para el Registro de Ventas
        getContentPane().add(panelrv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 560));
        panelrv.revalidate();
        panelrv.repaint();
        panelrv.setVisible(false);

        // 2- Panel para el Nuevo Producto
        getContentPane().add(panelnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 560));
        panelnp.revalidate();
        panelnp.repaint();
        panelnp.setVisible(false);

        // 3- Panel para buscar el Producto
        getContentPane().add(panelbp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 560));
        panelbp.revalidate();
        panelbp.repaint();
        panelbp.setVisible(false);
    }

    private void PanelContenido(int nBtn) {
        switch (nBtn) {
            case 1:
                jTabbedPane1.setVisible(true);
                panelrv.setVisible(false);
                panelnp.setVisible(false);
                panelbp.setVisible(false);
                break;
            case 2:
                jTabbedPane1.setVisible(false);
                panelrv.setVisible(true);
                panelnp.setVisible(false);
                panelbp.setVisible(false);
                break;
            case 3:
                jTabbedPane1.setVisible(false);
                panelrv.setVisible(false);
                panelnp.setVisible(true);
                panelbp.setVisible(false);
                break;
            case 4:
                jTabbedPane1.setVisible(false);
                panelrv.setVisible(false);
                panelnp.setVisible(false);
                panelbp.setVisible(true);
                break;
        }
    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jfmrLicoreria().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void ContenidojPanel2() {
        XYDataset dataset = createDatasetTwo();
        chart_2 = ChartFactory.createXYLineChart(
                "GRÁFICO DE LINEA CON CANTIDAD DE PRODUCTOS VENDIDOS", //Chart Title
                "TOTAL DE PRODUCTOS", // Category axis
                "COSTO DE PRODUCTOS", // Value axis
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        //XYPlot plot = chart.
        ChartPanel panel = new ChartPanel(chart_2);
        
        XYPlot plot = chart_2.getXYPlot();
        var renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, new Color(0, 102, 0));
        renderer.setSeriesStroke(0, new BasicStroke(3.0f));
        plot.setRenderer(renderer);

       //panel.setSize(2500, 1500);
        //jPanel2.add(panel);
        JScrollPane scroll = new JScrollPane(panel);
        scroll.setSize(920, 480);
        //scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        //scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        
        //scroll.setBounds(4, 242, 425, 100);	 
        jPanel2.add(scroll);
        scroll.setVisible(true);

        //pack();
    }

    private XYDataset createDatasetTwo() {
        var series1 = new XYSeries("Ventas Licoreria Señora Wilma");
//        series1.add(18, 530);
//        series1.add(20, 580);
//        series1.add(25, 740);
//        series1.add(30, 901);
//        series1.add(40, 1300);
//        series1.add(50, 2219);

//        var series2 = new XYSeries("2016");
//        series2.add(18, 567);
//        series2.add(20, 612);
//        series2.add(25, 800);
//        series2.add(30, 980);
//        series2.add(40, 1210);
//        series2.add(50, 2350);
        series1.add(0, 0, true);
        ProductoVendido nrv = new ProductoVendido(0, 0, 0.0, 0);
        Object[][] obj = nrv.BuscarTotalVenta();
        for (Object[] objects : obj) {
            int xx = Integer.parseInt(String.valueOf(objects[0]));
            Double yy = Double.parseDouble(String.valueOf(objects[1]));
            System.out.println("xx: " + xx + " yy: " + yy);
            series1.add(xx, yy);
        }
        
        var dataset = new XYSeriesCollection();
        dataset.addSeries(series1);
        //dataset.addSeries(series2);

        return dataset;
    }
/*
    private CategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        Producto pro = new Producto("", 0, 0.0, 0);
        Object[][] product_list = pro.BuscarProductoChart();

        for (Object[] product_list1 : product_list) {
            String rowkey = String.valueOf(product_list1[0]);
            int valor = Integer.parseInt(String.valueOf(product_list1[1]));

            dataset.addValue(valor, rowkey, "");
        }
        // Population in 2005
//        dataset.addValue(10, "Ruskaya", "");
//        dataset.addValue(15, "Corona", "");
//        dataset.addValue(20, "Pilsen", "");
//        dataset.addValue(4, "Ron Blanco", "");
//        dataset.addValue(4, "Pisco Blanco", "");
//        dataset.addValue(90, "Chin", "");
//        dataset.addValue(25, "hina", "");
//        dataset.addValue(40, "Cina", "");

        // Population in 2010
        dataset.addValue(15, "USA", "2010");
        dataset.addValue(20, "India", "2010");
        dataset.addValue(25, "China", "2010");

        // Population in 2015
        dataset.addValue(20, "USA", "2015");
        dataset.addValue(25, "India", "2015");
        dataset.addValue(30, "China", "2015");
        return dataset;
    }
*/
    private void BtnClick() {

        try {
            //con este funciona
            //ChartUtilities.saveChartAsPNG(new File("histogram.png"), chart, 450, 400);
            //pruebas con este
            LocalDateTime myDate = LocalDateTime.now();
            DateTimeFormatter myDateFormat = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String datenow = myDate.format(myDateFormat);
            String path = "imagen/grafico2/grafico " + datenow + ".png";
            ChartUtilities.saveChartAsPNG(new File(path), chart_2, 1920, 1080);
            /*} catch (IOException ex) {
            System.out.println("Error de crear archivo");
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        } catch (IOException ex) {
            System.out.println("Error guardar grafica:2");
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private int Message(String message) {        
        SiNoDialog dialog = new SiNoDialog(this, true);
        dialog.SetTextOption(message);
        dialog.setVisible(true);
        int answ = dialog.getReturnStatus();

        
    
        return answ;
    }
    
    /// =------------------------GRAFICO 1 ---------------------
    
    private void contenidoJPanel1(){
        CategoryDataset dataset = createDataset();

        chart_1 = ChartFactory.createBarChart3D(
                "GRÁFICO DE BARRAS CANTIDAD DE PRODUCTOS EN LA TIENDA", //Chart Title
                "TOTAL DE PRODUCTOS", // Category axis
                "CANTIDAD POR PRODUCTO", // Value axis
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );                 
        ChartPanel panel = new ChartPanel(chart_1);
        panel.setVisible(true);
        panel.setMinimumSize(new Dimension(1920,1080));
        panel.setSize(1920,1080);
            
        JScrollPane scroll = new JScrollPane(panel);
        scroll.setSize(920, 485);
        scroll.setVisible(true);
        jPanel1.add(scroll);
    }
    private CategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        Producto pro = new Producto("",0,0.0,0);
        Object[][] product_list = pro.BuscarProductoChart();
        
        for (Object[] product_list1 : product_list) {
            String rowkey = String.valueOf(product_list1[0]);
            int valor = Integer.parseInt(String.valueOf(product_list1[1]));
            
            dataset.addValue(valor, rowkey,"");
        }
        /*Random rd = new Random();
        for (int i = 1; i < 50; i++) {
                int x = rd.nextInt(99);
            dataset.addValue(x, ("Pr"+x), "");
        }*/
        // Population in 2005
//        dataset.addValue(10, "Ruskaya", "");
//        dataset.addValue(15, "Corona", "");
//        dataset.addValue(20, "Pilsen", "");
//        dataset.addValue(4, "Ron Blanco", "");
//        dataset.addValue(4, "Pisco Blanco", "");
//        dataset.addValue(90, "Chin", "");
//        dataset.addValue(25, "hina", "");
//        dataset.addValue(40, "Cina", "");

        /*// Population in 2010
        dataset.addValue(15, "USA", "2010");
        dataset.addValue(20, "India", "2010");
        dataset.addValue(25, "China", "2010");

        // Population in 2015
        dataset.addValue(20, "USA", "2015");
        dataset.addValue(25, "India", "2015");
        dataset.addValue(30, "China", "2015");*/
        return dataset;
    }
    public void BtnClick_1() {
        try {
            //con este funciona
            //ChartUtilities.saveChartAsPNG(new File("histogram.png"), chart, 450, 400);
            //pruebas con este
            //ChartUtilities.saveChartAsPNG(new File("imagen/histogram.png"), chart, 450, 400);
            LocalDateTime myDate = LocalDateTime.now();
            DateTimeFormatter myDateFormat = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String datenow = myDate.format(myDateFormat);
            String path = "imagen/grafico1/grafico "+datenow+".png";
            ChartUtilities.saveChartAsPNG(new File(path), chart_1, 1920, 1080);
        } catch (IOException ex) {
            System.out.println("Error de crear archivo");
            java.util.logging.Logger.getLogger(jfmrLicoreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
}
